#!/usr/bin/env python3
# LingoInk bitmap font generator.
# Renders a TTF/OTF into 1-bpp C headers in the LgFont format (see
# src/ui/LgFont.h). Run from repo root or pass explicit paths.
#
# Usage:
#   python tools/make_font.py --ttf Inter.ttf --size 28 --name body28 \
#       --out src/ui/fonts/body28.h \
#       --ranges "20-7E,410-44F,401,451,2013,2014,2018,2019,201C,201D,2026,2022,B0,B7,AB,BB,2190-2193,2713,2717"
#
# Requires: pip install freetype-py

import argparse
import sys
from pathlib import Path

import freetype


def parse_ranges(spec: str):
    ranges = []
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            a, b = part.split("-")
            ranges.append((int(a, 16), int(b, 16)))
        else:
            cp = int(part, 16)
            ranges.append((cp, cp))
    ranges.sort()
    return ranges


def render_glyph(face, cp: int, px: int):
    """Return (bitmap rows as list of bytes MSB-first, w, h, advance, left, top)."""
    flags = freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL
    if face.load_char(chr(cp), flags):
        # freetype-py returns an error code (truthy) when loading fails;
        # a successful load returns None.
        return None
    if True:
        slot = face.glyph
        bmp = slot.bitmap
        w, h = bmp.width, bmp.rows
        advance = slot.advance.x >> 6
        left = slot.bitmap_left
        top = slot.bitmap_top
        pitch = bmp.pitch
        buf = bmp.buffer
        rows = []
        for y in range(h):
            row_bits = []
            base = y * pitch
            for x in range(w):
                alpha = buf[base + x]
                row_bits.append(1 if alpha >= 128 else 0)
            # pack to bytes, MSB first
            nbytes = (w + 7) // 8
            packed = bytearray(nbytes)
            for x, bit in enumerate(row_bits):
                if bit:
                    packed[x >> 3] |= 0x80 >> (x & 7)
            rows.append(bytes(packed))
        return rows, w, h, advance, left, top
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True, help="pixel size")
    ap.add_argument("--name", required=True, help="C identifier base, e.g. body28")
    ap.add_argument("--out", required=True, help="output .h path")
    ap.add_argument("--ranges", required=True, help="hex ranges, comma separated")
    ap.add_argument("--threshold", type=int, default=128)
    args = ap.parse_args()

    face = freetype.Face(args.ttf)
    face.set_pixel_sizes(0, args.size)

    ranges = parse_ranges(args.ranges)

    bitmaps = bytearray()
    glyphs = []          # (cp, w, h, advance, left, top, dataLen, dataOffset)
    intervals = []       # (first, last, glyph_index)

    for first, last in ranges:
        seen_any = False
        idx_first = len(glyphs)
        for cp in range(first, last + 1):
            if cp == 0:
                continue
            rendered = render_glyph(face, cp, args.size)
            if rendered is None:
                continue
            rows, w, h, advance, left, top = rendered
            if w == 0 or h == 0:
                # space and other blank glyphs still advance the cursor
                glyphs.append((cp, 0, 0, advance, 0, 0, 0, len(bitmaps)))
                seen_any = True
                continue
            offset = len(bitmaps)
            nbytes = (w + 7) // 8
            for row in rows:
                bitmaps += row
            glyphs.append((cp, w, h, advance, left, top, nbytes * h, offset))
            seen_any = True
        if seen_any:
            intervals.append((first, last, idx_first))

    # merge adjacent intervals to keep the table small
    merged = []
    for first, last, off in intervals:
        if merged and first <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], last), merged[-1][2])
        else:
            merged.append((first, last, off))

    ascender = face.size.ascender >> 6
    descender = face.size.descender >> 6
    height = face.size.height >> 6  # baseline-to-baseline

    name = args.name
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write("// Generated by tools/make_font.py — DO NOT EDIT.\n")
        f.write(f"// Source font: {Path(args.ttf).name}, {args.size}px, 1bpp.\n")
        f.write(f"#pragma once\n#include <stdint.h>\n\n")
        f.write(f"static const uint8_t {name}_bitmap[] = {{\n")
        for i in range(0, len(bitmaps), 16):
            chunk = bitmaps[i:i + 16]
            f.write("  " + ",".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")

        f.write(f"static const LgGlyph {name}_glyphs[] = {{\n")
        for cp, w, h, adv, left, top, dlen, off in glyphs:
            f.write(f"  {{{w},{h},{adv},{left},{top},{dlen},0x{off:X}}},  // U+{cp:04X}\n")
        f.write("};\n\n")

        f.write(f"static const LgInterval {name}_intervals[] = {{\n")
        for first, last, off in merged:
            f.write(f"  {{0x{first:X},0x{last:X},{off}}},\n")
        f.write("};\n\n")

        f.write(
            f"static const LgFont {name} = {{\n"
            f"  \"{name}\",\n"
            f"  {name}_bitmap,\n"
            f"  {name}_glyphs, {len(glyphs)},\n"
            f"  {name}_intervals, {len(merged)},\n"
            f"  {height if height > 0 else args.size}, {ascender}, {descender},\n"
            f"}};\n"
        )

    total_glyph_bytes = len(bitmaps)
    print(f"{out}: {len(glyphs)} glyphs, {len(merged)} intervals, "
          f"bitmap {total_glyph_bytes} bytes, advanceY={height}, "
          f"asc={ascender}, desc={descender}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
